spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw-leasing-demo
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
